services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  backend:
    build: backend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  frontend:
    build: frontend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - db

  adminer:
    image: adminer:latest
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST}
      - ADMINER_DEFAULT_USER=${DB_USER}
      - ADMINER_DEFAULT_PASSWORD=${DB_PASSWORD}
      - ADMINER_DEFAULT_TYPE=postgresql
      - ADMINER_DEFAULT_PORT=${DB_PORT}
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

